# Generated by Django 3.0.7 on 2020-11-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile', verbose_name='profile image'),
        ),
    ]
