# Generated by Django 3.0.7 on 2020-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201106_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile', verbose_name='profile image'),
        ),
    ]
