# Generated by Django 3.0.7 on 2020-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201126_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile', verbose_name='Profile_image'),
        ),
    ]
