# Generated by Django 3.0.7 on 2020-11-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_readinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='post',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='post',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Post'),
        ),
    ]
