# Generated by Django 3.0.7 on 2020-11-27 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20201127_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(related_name='post_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReadingList',
        ),
    ]
