# Generated by Django 3.1.4 on 2020-12-17 05:39

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201204_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True),
        ),
    ]
