# Generated by Django 3.1.4 on 2020-12-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201217_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title',)},
        ),
    ]
