# Generated by Django 3.1.5 on 2021-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210108_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='/profile/default.jpg', upload_to='profile', verbose_name='Profile_image'),
        ),
    ]
